jsconfjp/jsconf.jp

2019/src/components/HeaderMobile.tsx

Hi JSConf JP team!
I open this PR because I found that in the mobile view when you scroll down a bit and scroll up to click the Hamburger menu the header will disappear. I think it is really annoying.
If I understand correctly, this behavior is caused by Headroom re-rendering so I separated them from the HeaderMobile.
After that, I found my changes affected the display height.
When you opened a Menu and changed the language, the height between the Headroom and content will be fixed to the size of a Menu. so I decided to make sure the Menu will be disappeared after changing the language.
**This is the final result:**
Clicking Hamburger.
Changing languages.
However, you might see it already, there is no expanding space anymore. The Menu will display over the content.
Feel free to comment, …

Fix header mobile unpin

---

2019/src/components/Speaker.tsx
2019/src/pages/schedule.tsx
2019/src/templates/speaker.tsx
2019/src/util/languages.ts

It's possible to have `en-us`, `en-au` and so on `en-*` languages so it
would be easier to check the language with `ja`.
So, the issue here is, if we only check `en-*` languages with `=== 'en'`, the default `en` would break for those who set language with `en-us` or so.
| Before | After |
| ------ | ------ |
| <img width="745" alt="image" src="https://user-images.githubusercontent.com/6782666/68547279-10c60200-0423-11ea-85d0-935f720fbcb1.png"> | <img width="758" alt="image" src="https://user-images.githubusercontent.com/6782666/68547282-1a4f6a00-0423-11ea-9ee7-6ed49483417b.png"> |

Fix default language to English

---

2021/src/components/LanguageSwitch.tsx

ページ上端の言語選択 UI から `日本語` をクリックした後、ページをリロードしたり再訪したりすると、以下のスクリーンショットの通り、本文が日本語であるにも関わらず言語選択 UI の現在状態が EN となってしまうようでした。
以下の issue, 記事によると、Gatsby が呼び出す [ReactDOM.hydrate()](https://reactjs.org/docs/react-dom.html#hydrate) は、予め描画した HTML の属性がブラウザで描画した場合と異なっていたとき、ブラウザで描画されたはずの属性が反映されなくなってしまうようでした。
https://github.com/gatsbyjs/gatsby/discussions/17914
https://www.joshwcomeau.com/react/the-perils-of-rehydration/
今回は、この問題により言語選択 UI （ LanguageSwitch ）の a タグの href 属性が反映されなくなっているように見えました。
本 PR で、上の記事で紹介されているものと同様のワークアラウンドを追加してみました。
瑣末で恐縮ですが、ご検討いただけますと幸いです。

fix: re-render the component on the client side

---

2021/src/data/talks.yml

fix: typo (Twillio -> Twilio)

---

2022/src/i18n/en.ts
2022/src/i18n/ja.ts

https://jsconf.jp/2022/ トップページのチケット登録の表記を `購入する/Buy Tickets` から `参加登録/Registration` に変更しました。

change: チケットを購入する/Buy Tickets -> 参加登録/Registration

---

2022/src/data/talks.yaml

トークの趣旨は変わりませんが、タイトルだけ微妙に変えたいです

トークタイトル変更 `Current state of Npm support in Deno` -> `About npm: support of Deno`

---

2022/src/components/Layout.tsx

トップページをスマートフォンで表示した時に、
「Join us」ボタンと、「TOPへ戻る」ボタンが重なっていたので修正しました。
レビューお願いいたします 🙇‍♂️ 
- 修正前
- 修正後

Fix: Fix button style when on smart phone

---

2023/src/data/members.yaml
README.md

今年のJSConf JPにクルーとして参加させていただきますので追加します。
ついでに`READ.md`からちょっとした誤字を見つけたので、修正しました。
This PR adds additional crew member info, and fixes small typo in the `READ.md`.

Add a crew member & fix typo

---

2023/package-lock.json
2023/package.json
2023/src/components/Speaker.tsx
2023/src/i18n/en.ts
2023/src/i18n/ja.ts
2023/src/pages/schedule.tsx

発表時間の表示(長さ)を追加, 発表場所(on-site or remote)の表示を追加, i18nサポート, そのほかデザイン調整

---

2023/src/templates/speaker.tsx

fix: using translation for speaker breadcrumb

---

2023/src/components/RoomLegend.tsx
2023/src/templates/speaker.tsx

Instead of having the one color for all talks in the speaker display this PR uses the color of the Room for the session details

Use Track color in the Schedule Display

---

2023/src/pages/schedule.tsx

色が見えない人が区別できるように
https://github.com/jsconfjp/jsconf.jp/assets/914122/45ec78b2-6843-4a3a-a219-e8bea9149c94

a11y スケジュールのトラック名をバブルに

---

2023/gatsby-node.js
2023/package-lock.json
2023/package.json
2023/src/data/types.ts
2023/src/pages/schedule.tsx
2023/src/templates/speaker.tsx

- add social site links to the speaker page

update: speaker add social site links

---

2023/gatsby-node.js
2023/src/components/Tags.tsx
2023/src/pages/schedule.tsx
2023/src/styled.d.ts
2023/src/templates/speaker.tsx

 Same Tags in Speaker as in Schedule

---

2024/src/components/Sponsor.tsx

Sponsorsページ上の平文URLを、クリック可能なハイパーリンクに変換しました。

Convert text URLs to hyperlinks on Sponsors page

---

2024/src/i18n/en.ts

トップページに記載されているJSConf Japanのイベント回数を4回目から5回目に更新しました。
- 変更前: "This is the fourth time event of jsconf in Japan."
- 変更後: "This is the fifth time event of jsconf in Japan."

Update event count from 4th to 5th on top page

---

2024/gatsby-node.js
2024/src/components/InlineLink.tsx
2024/src/components/RoomLegend.tsx
2024/src/templates/schedule.tsx
2024/src/util/rangeTimeBoxes.ts

印刷のためにやくに経ちますが、それぞれのトラックをクリックするとそのトラックだけを表示するようになります。ちゃんとリンクできるように `/schedule/A` などの URL も追加しました。
https://github.com/user-attachments/assets/10de3bfd-11ac-4d2a-b87b-31a163a03459
https://github.com/user-attachments/assets/12e33ba4-a4f0-45a4-bab2-615b022fafcc

トラックをクリックしますように

---

2024/src/templates/schedule.tsx

With the merge of #400 there were "(Closed)" displays added for Track D to look cleaner on the print version. Unfortunately this looks weird in the mobile version. ↓
This PR hides all but the A breaks in the mobile view, removing confusion.

Hide breaks that are not for the entire building in the mobile view

---

2024/src/data/talks.yaml

以下のIssueにある、Markdownの記法の問題を修正しています
* https://github.com/jsconfjp/jsconf.jp/issues/489
* https://github.com/jsconfjp/jsconf.jp/issues/499
しないこと: 翻訳のテキストは気になった部分があっても手を加えない。
リンクの修正
* https://deploy-preview-500--jsconf-jp-preview.netlify.app/2024/talk/aakansha-doshi/
改行の修正
* https://deploy-preview-500--jsconf-jp-preview.netlify.app/2024/talk/mizdra/
* https://deploy-preview-500--jsconf-jp-preview.netlify.app/2024/talk/mesut-durukal/
* https://deploy-preview-500--jsconf-jp-preview.netlify.app/2024/talk/sosuke-suzuki/

fix: markdown description text

---

2024/src/components/Breadcrumb.tsx
2024/src/data/talks.yaml
2024/src/templates/schedule.tsx
2024/src/templates/speaker.tsx

変更内容
* 発表タイトルにMarkdownが含まれる場合にParseされるように調整しました。
* 発表タイトルの大文字・小文字に意味があるケースがあったため、`uppercase`のスタイルを削除しました（この変更が不要な場合はご指摘ください）
* パンくずリストのスタイルを調整しました
対応ページ
* https://deploy-preview-502--jsconf-jp-preview.netlify.app/2024/talk/yuji-sugiura/
タイトルの大文字小文字が意味があるようなページ
* https://deploy-preview-502--jsconf-jp-preview.netlify.app/2024/talk/earthbrain/
* https://deploy-preview-502--jsconf-jp-preview.netlify.app/2024/talk/mizdra/

fix: title style

---

2025/src/app/[locale]/page.tsx

I tried various colors to maintain a certain contrast ratio, but decided that none of them matched the atmosphere of the site.
According to the definition of contrast ratio, even with the current colors, large text would pass, so I solved the problem by changing the size of the buttons.

fix: a11y issues on button contrast ratio

---

2025/src/components/Chip.tsx
2025/src/components/TimeTable.tsx
2025/src/lib/getTrackClassNames.ts

> Dynamic class names
> Since Tailwind scans your source files as plain text, it has no way of understanding string concatenation or interpolation in the programming language you're using.
>
> &mdash; [Detecting classes in source files - Core concepts - Tailwind CSS](https://tailwindcss.com/docs/detecting-classes-in-source-files#dynamic-class-names)

fix: do not use dynamic class name
