2019/scripts/import-talks.ts, 2019/src/data/speakers.yaml, 2019/src/data/talks.yml
Remove duplicated speakers
AsIs:
ToBe:
=> Remove deprecated speakers

2019/src/components/HeaderMobile.tsx
=> fix: use title tag instead of title attribute

2019/src/components/Footer.tsx, 2019/src/i18n/en.ts, 2019/src/i18n/ja.ts
Company Address is needed by Payment Systems on website.
=> feat: add company address on footer

2021/gatsby-ssr.js, 2021/src/components/Seo.tsx, 2021/src/pages/index.tsx
https://github.com/gatsbyjs/themes/tree/master/packages/gatsby-theme-i18n-react-i18next
=> Fix i18n during build

2021/gatsby-config.js
=> Add link to register tickets

2021/gatsby-config.js, 2021/src/components/Footer.tsx, 2021/src/components/HamburgerMenu.tsx, 2021/src/components/Header.tsx, 2021/src/components/HeaderMobile.tsx, 2021/src/components/Layout.tsx, 2021/src/components/SpeakerList.tsx, 2021/src/components/Sponsor.tsx, 2021/src/components/SponsorList.tsx, 2021/src/pages/index.tsx
- Don't have to show/hide pages/index.tsx manually
- Don't have to show/hide menu items manually
=> Tweak for ease of maintenance

2021/src/data/talks.yml
```
14:30-15:00 (トラックB)
アクセシブルなフロントエンド開発のこれまでとこれから
by okuto-oyama
```
```
16:20-16:50 (トラックA)
AMP キャッシュを超えるシステムを自社ドメインで実現する方法
by junya-kani
```
について発表者の時間枠を入れ替えました。
=> Update for talks schedule

2022/src/data/members.yaml
先日参加させていただいた篠田です 🙏 
メンバーに追加させていただきました！
ご確認よろしくお願いいたします。
=> update members 

2022/gatsby-node.js, 2022/src/components/Speaker.tsx, 2022/src/data/talks.yaml, 2022/src/templates/speaker.tsx
=> Embed talk recordings in talk pages

2023/src/i18n/en.ts
ultra nit but I believe this year's JSConf JP is the forth time according to the repository.
=> JSConf JP 2023 is the fourth time?

2023/src/data/members.yaml
=> add Jake to volunteers

netlify.toml
Basic security headers:
I added basic security headers, like X-Frame-Options, X-XSS-Protection and X-Content-Type-Options
Content Security Policy:
In the first iteration, I only added report only rules to detect mistakes. Modifications will be made after everything has been tested.
Permissions Policy
Disable all non need featues to prevent security issues.
=> chore(security): add basic CSP and other security headers

2023/src/data/members.yaml
I am unable to attend JSConf due to a work related task. Thank you for the invite!
=> Revert "add Jake to volunteers"

2023/gatsby-config.js
The sponsors have been decided.
=> Remove Call for Sponsors

2023/src/components/Layout.tsx, 2023/src/components/Speaker.tsx, 2023/src/components/SpeakerList.tsx, 2023/src/pages/speakers.tsx, 2023/src/theme.ts, 2023/src/util/rgba.ts
スピーカーのコンポーネントを使う上にデザインアップデート
https://github.com/jsconfjp/jsconf.jp/assets/914122/c16ac6f1-6d5f-4051-b5f3-bb6e685688f8
=> スピーカー一覧デザインアップデート

2023/src/data/talks.yaml
当日に管理しやすいように全てのリモートスピーカーを A → D に変化しました。そして、リモートの LT を一番最後にしました。
=> リモートLT を終わりに

2023/gatsby-config.js
=> チケットURLを外す

2024/src/data/members.yaml
=> chore: add himenon to the staff

2024/src/data/members.yaml
=> add Teruhisa to members

2024/gatsby-config.js, 2024/src/components/EventSpeakers.tsx, 2024/src/data/speakers.yaml, 2024/src/data/sponsors.yaml, 2024/src/data/talks.yaml, 2024/src/data/types.ts, 2024/src/pages/index.tsx, 2024/src/pages/schedule.tsx, 2024/src/templates/speaker.tsx, 2024/src/util/generateTimetable.ts
=> chore: run prettier

2024/src/data/members.yaml
=> chore: add murata kaito as member

2024/package-lock.json, 2024/package.json, 2024/src/components/EventTime.tsx, 2024/src/components/Hero.tsx, 2024/src/components/HeroCountdown.tsx, 2024/src/i18n/en.ts, 2024/src/i18n/ja.ts, 2024/src/util/useCountdown.tsx
時間がゼロになると表示しなくなります。`date-fns` の代わりに `Temporal` を使うように
=> 残りの時間の表示追加

2024/src/data/talks.yaml
Speaker not connected in data structure.
=> Fix: Reference talk/speaker eiji-kitamura

2024/src/components/Breadcrumb.tsx, 2024/src/components/Footer.tsx, 2024/src/styled.d.ts, 2024/src/theme.ts
=> improve breadcrumbs and footer colors

2024/src/components/LanguageSwitch.tsx, 2024/src/components/Layout.tsx, 2024/src/components/Member.tsx, 2024/src/components/Title.tsx, 2024/src/pages/index.tsx
=> accessibility and seo fixes

2024/src/data/talks.yaml
Hello 👋🏻
The description of my talk was too long hence I have shortened it. Please let me know if this is good.
I will leave the Japanese translation to you.
=> chore: update description of my talk :)

2024/.prettierrc
we added windows settings to fix line endings.
=> Fixed prettier for windows

2024/src/components/VenueMap.tsx, 2024/src/images/venue-map-ja.svg
Closes #513 |
@martinheidegger
=> add venue map translation

2024/src/data/talks.yaml, 2024/src/templates/schedule.tsx
#489 
@martinheidegger  Fixes missing language tags
=> add missing lang tags to talks

2024/src/data/talks.yaml
Correct the talk title and add slide url and remove extra whitespaces
=> feat(talks): update Csaba Tamas talk title and slide url

2025/messages/en.json, 2025/messages/ja.json, 2025/src/app/[locale]/page.tsx, 2025/src/app/[locale]/sponsors/page.tsx, 2025/src/components/SponsorGrid.tsx, 2025/src/components/SponsorLogo.tsx, 2025/src/components/Team.tsx, 2025/src/constants/sponsors.ts
こんな見た目になります
まだダミーデータしか入ってないので本番では非表示です
=> feat: implement Sponsor list item

2025/src/components/GlobalNavigation.tsx, 2025/src/components/Hero.tsx, 2025/src/components/TeamMember.tsx, 2025/src/constants/team.ts
=> perf: optimize fetchPriority

2025/messages/en.json, 2025/messages/ja.json, 2025/src/app/[locale]/page.tsx, 2025/src/app/[locale]/venue/page.tsx, 2025/src/components/Button.tsx, 2025/src/components/Venue.tsx, 2025/src/constants/venue.ts
=> feat: apply venue

2025/next.config.ts, 2025/src/app/layout.tsx, 2025/src/components/LanguageSwitcher.tsx
https://nextjs.org/docs/app/api-reference/config/next-config-js/viewTransition
=> feat: enable ViewTransition API

2025/src/app/[locale]/layout.tsx, 2025/src/app/[locale]/page.tsx, 2025/src/app/globals.css, 2025/src/components/PageContainer.tsx, 2025/src/components/Team.tsx, 2025/src/components/TeamMember.tsx, 2025/src/constants/team.ts
=> refactor: margin & background colors

2025/src/constants/team.ts
=> Adding mai-ya, shimataro

2025/src/constants/team.ts
=> feat: add hannah info

2025/src/constants/talks.ts
=> fix: jxck content

2025/src/constants/talks.ts
from: https://x.com/i_am_canalun/status/1971153510277447979
=> fix: change session language

2025/messages/en.json, 2025/messages/ja.json, 2025/src/components/SessionCard.tsx, 2025/src/constants/schedule.ts
=> feat: stream keynotes to other tracks

2025/src/constants/team.ts
Hey all, 
I helped filled out the survey for speakers earlier this month. @martinheidegger  mentioned it might be a good idea to add myself here. I can also help out with the website and event as well! Looking forward to seeing you all in November!
=> add Jake to team.ts
